apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/nmshd/connector:3.11.4
          imagePullPolicy: Always
          name: connector
          env:
            - name: transportLibrary__baseUrl
              value: https://nmshd-bkb.demo.meinbildungsraum.de/
            - name: transportLibrary__platformClientId
              valueFrom:
                secretKeyRef:
                  key: PLATFORM_CLIENT_ID
                  name: nmshd
            - name: transportLibrary__platformClientSecret
              valueFrom:
                secretKeyRef:
                  key: PLATFORM_CLIENT_SECRET
                  name: nmshd
            - name: database__connectionString
              value: mongodb://mongo:27017
            - name: database__dbName
              value: mydb
            - name: infrastructure__httpServer__apiKey
              valueFrom:
                secretKeyRef:
                  key: HTTP_API_KEY
                  name: nmshd
            - name: https_proxy
              value: http://squid:3128
          ports:
            - containerPort: 80
